spring:
  application:
    name: hwplat-zipkin
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://hwplat-eureka-1111:1111/eureka/,http://hwplat-eureka-1112:1112/eureka/,http://hwplat-eureka-1113:1113/eureka/
  instance:
    prefer-ip-address: true
logging:
  file: logs/${spring.application.name}.log
  level:
    org:
      springframework: WARN




  #server:
    #enable-self-preservation: false
   #eviction-interval-timer-in-ms: 3000
   # wait-time-in-ms-when-sync-empty: 6000000
   # peer-eureka-nodes-update-interval-ms: 60000

