spring:
  application:
    name: hwplat-eureka
server:
  port: 1111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://hwplat-eureka:1111/eureka/
logging:
  file: logs/${spring.application.name}.log
  level:
    org:
      springframework: WARN





