spring:
  application:
    name: hwplat-eureka
server:
  port: 1111

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://hwplat-eureka:1111/eureka/
logging:
  file: /mnt/logs/${spring.application.name}.log
  level:
    org:
      springframework: WARN
